package com.revature.data;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import com.revature.service.ConnectionFactory;
import com.revature.trms.Event;
import com.revature.trms.Status;

public class StatusDAOImpl implements StatusDAO {
	Connection connection;

	public StatusDAOImpl() throws ClassNotFoundException {
		connection = ConnectionFactory.getConnected();
	}

	@Override
	public int create(Status newStatus) throws SQLException {
		// TODO Auto-generated method stub
		
		String sql = "Insert into Status(id,status_name)" + 
				"Values(default,?);";
		
	try {
	PreparedStatement preparedStatement = connection.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS);
	
	preparedStatement.setString(1,newStatus.getStatusName());
	
	int count = preparedStatement.executeUpdate();
	
	ResultSet resultSet = preparedStatement.getGeneratedKeys();
	
	if(count>0) {
		System.out.println("Status added!");
		// return the id generated by this entry
		resultSet.next();
		int id = resultSet.getInt(1);
		return id;
	}
	}
	catch(SQLException e) {
		e.printStackTrace();
		System.out.println("Something went wrong!");
	}
	
	return -1;
	}

	@Override
	public Status getById(long id) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List<Status> getAll() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void update(Status updatedObj) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void delete(Status objToDelete) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void deleteById(int id) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public int create(Event newObj) {
		// TODO Auto-generated method stub
		return 0;
	}
}
